### PR TITLE
`makeContentBlockQuery`: optional arg

### PR DESCRIPTION
**Pull request by gksander**
Little sprinkle sprinkle of convenience.

### CODE REVIEW

**Comment by fritz-c** [comment]
Max explained to me that I could do the query validation/type grabbing as I wanted with
```js
q.select({'_type == "block"': ["{ ... }", q.contentBlock()] })
```
, so there may not be much of a use case for `makeContentBlockQuery` for me in the first place, and it may be misleading to expose it when it can't actually be used as I initially thought it could be used:
```js
q.select({'_type == "block"': makeContentBlockQuery() })
// ^ this won't work. The children and any other array properties do not get fetched
```

**Comment by gksander** [comment]
I see, I see. So in your opinion, is it best to close this PR and then revert the previous related one so that we're no longer exposing that internal method?

**Comment by fritz-c** [comment]
@gksander Yes, sorry for the sudden 180.

**Comment by gksander** [comment]
hey, no worries at all!

**Pull request closed without merging**
