### PR TITLE
formideploy setup

### PR DESCRIPTION
**Pull request by gksander**
Setting up formideploy to deploy docs to `formidable.com/open-source/groqd`. Still need to get TF/AWS access keys setup.

### CODE REVIEW

**Review by carloskelly13 — APPROVED** [review]
So we're using formideploy here since we're deploying as a sub route of our dotcom over deploying the docs site on Vercel and pointing a subdomain like grodq.formidable.dev.

**Comment by gksander** [comment]
Yep, that's right – for the time being. Once we migrate to the new `formidable.com` architecture, we can do the "zones" approach and just rewrite into the Vercel-deployed site, but in the interim we'll do a formideploy setup to match the other docs configurations.

**Comment by ryan-roemer** [comment]
I don't totally follow the `grodq.formidable.dev`. As long as we don't mess with base url still building always to have `/open-source/groqd/` in all (dev, staging, prod) cases, it doesn't really matter...

**Review by ryan-roemer — APPROVED** [review]
LGTM

**Comment by carloskelly13** [comment]
Some of our docs sites for smaller projects exist as subdomains on formidable.dev and we should probably unify in one direction or another.

**Comment by ryan-roemer** [comment]
> Some of our docs sites for smaller projects exist as subdomains on formidable.dev and we should probably unify in one direction or another.

Yeah, that's fine to do if we want to! I'm only really concerned with the tried and true way we've blown off our toes in the past wherein we have dev and/or staging have a root of `DOMAIN.com` and our production be `DOMAIN.com/open-source/NAME`. As long as we adhere to our rule that subpath structure is identical in dev + staging + prod, I'm a happy camper 😄

**Comment by gksander** [comment]
I'd imagine that from an SEO/analytics perspective, having everything under the root domain is the most friendly. But TBH, I was just doing what AMA/Owl/Zephyr did.

**Comment by carloskelly13** [comment]
Agreed. I suspect the subdomain formidable.dev approach was used because it was easier to stand up for our team and get something deployed.

**Pull request merged**
