### PR TITLE
added content blocks list helper

### PR DESCRIPTION
**Pull request by iduuck**
**Motivation:**
I used the `q.contentBlock` helper in one of my projects, and spend a lot of time, to debug, why it is telling me, that it is expecting an object, and received an array, until I saw, that `contentBlock` needs to be used with an array.

This helper helps mitigating this issue.

**TODO:** 
- [x] Helper function
- [x] Test for helper function
- [x] Documentation in README

### CODE REVIEW

**Review by gksander — COMMENTED** [review]
This is a great idea. I was talking to a colleague the other day that ran into the same problem!

Will you remove the pnpm lock file, and add a small blurb to the README and then tag me in a comment and we can get this merged/released ASAP!

**Comment by iduuck** [comment]
Done!

**Comment by iduuck** [comment]
done @gksander

**Review by gksander — APPROVED** [review]
🚀

**Pull request merged**
